<a href="https://colab.research.google.com/github/vishnu-777/python-openCV/blob/main/numpymatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.matrix([[3,2,4],[4,5,6],[7,6,5]])
print(a)
print(np.shape(a))
print(b,"\n",np.shape(b))

[[1 2 3]
 [4 5 6]]
(2, 3)
[[3 2 4]
 [4 5 6]
 [7 6 5]] 
 (3, 3)
